[supervisord]
nodaemon=true
user=user
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
loglevel=info

[program:postgresql]
command=/usr/lib/postgresql/15/bin/postgres -D /var/lib/postgresql/data
autostart=true
autorestart=true
priority=1
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mongodb]
command=mongod --dbpath /var/lib/mongodb --bind_ip_all
autostart=true
autorestart=true
priority=1
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:fastapi]
command=/home/user/app/start_fastapi.sh
autostart=true
autorestart=true
priority=10
startsecs=5
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=SQL_HOST="localhost",SQL_PORT="5432",SQL_USER="admin",SQL_PASSWORD="admin1234",SQL_DATABASE="eventry_db",MONGO_URI="mongodb://localhost:27017/eventry",MONGO_DB_NAME="eventry",PYTHONPATH="/home/user/app/backend",JWT_SECRET_KEY="SfNmwuzNKdne+pdHStUswFxXEuPvLcyeP69BQ7/QPgU="
